### ISSUE TITLE
Enable direct edit translation on the grid

### ISSUE THREAD

**Issue by jordimas** [ccoreilly/subdub-editor#10]
Feedback from Softcatalà group meeting.

When showing the grid:

![Captura de pantalla de 2024-12-14 16-46-36](https://github.com/user-attachments/assets/fd62209c-204d-4180-a986-64811bbd2454)

Allow to the user to edit the text by clicking on the text directly without needing to click edit.
The rational is that this will be the most common change

**Comment by ccoreilly** [comment]
This is implemented but was disabled. I recall it was not ideal. I will enable it again and let's see what the feedback is to improve the current UX.

**Comment by ccoreilly** [comment]
Fixed in https://github.com/Softcatala/subdub-editor/commit/aabb2eb0dd9b52632ecf9445e06706bdd0e48913
