### ISSUE TITLE
When changing the speaker, update the gender field

### ISSUE THREAD

**Issue by jordimas** [ccoreilly/subdub-editor#13]
When changing the speaker in a chunk, update the gender field also if it changes (e.g. from male to female).
If this is not done, the backend does not work well since it uses the speaker + gender to select voice.

**Comment by ccoreilly** [comment]
Fixed in https://github.com/Softcatala/subdub-editor/commit/d0de299bd03e59be6b6e0a67abc3a1fadbf578d2
