### ISSUE TITLE
Get voices from the end point 

### ISSUE THREAD

**Issue by jordimas** [ccoreilly/subdub-editor#6]
We should remove the hardcoded values:

https://github.com/Softcatala/subdub-editor/blob/main/src/services/MatxaSynthesisProvider.ts#L15

and replace this with a call to the backend that provides the voices.

This enables to make changes without doing a full client release

**Comment by ccoreilly** [comment]
Fixed in https://github.com/Softcatala/subdub-editor/commit/5654b4cc546d46ffe2999f15b7a715574e76bf60
